In [26]:
import numpy as np
import pandas as pd

In [27]:
df = pd.read_csv('customer.csv')

In [28]:
df.sample(5)

age gender review education purchased
40   39   Male   Good    School        No
12   51   Male   Poor    School        No
14   15   Male   Poor        PG       Yes
28   48   Male   Poor    School        No
39   76   Male   Poor        PG        No

In [29]:
# on revies and education we perform ordinal encoding because they are ordinal data 
# on purchased column we perform label encoding
# on gender we perform onehotencoding (not now)

In [30]:
df = df.iloc[:,2:]

In [31]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [32]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [33]:
X_train.head()

review education
11   Good        UG
38   Good    School
41   Good        PG
25   Good    School
27   Poor        PG

In [34]:
from sklearn.preprocessing import OrdinalEncoder

In [35]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [36]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [37]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [38]:
X_train

array([[2., 1.],
       [2., 0.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [0., 1.],
       [2., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [0., 2.]])

In [39]:
X_test

array([[0., 0.],
       [0., 2.],
       [0., 0.],
       [2., 2.],
       [1., 0.],
       [2., 1.],
       [2., 0.],
       [1., 2.],
       [2., 2.],
       [0., 1.]])

In [40]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [41]:
from sklearn.preprocessing import LabelEncoder

In [42]:
le = LabelEncoder()

In [43]:
le.fit(y_train)

LabelEncoder()

In [44]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [45]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [46]:
y_train

array([1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0])